[package]
name = "wave-function-collapse"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.120"
